In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.ndimage as ndimage
import glob, os, shutil, cv2, json, sys
from tqdm import tqdm
from pathlib import Path
import papermill as pm

sys.path.append('../..')
from Dataset.index import Normalization, getFiles

In [2]:
DATASET01 = {'path': '../dataset_74', 'n_images': 110}
DATASET02 = {'path': '../dataset_wu', 'n_images': None}

In [3]:
BASE_PATH = f'../Dataset/{Path().resolve().name}'
BASE_PATH

'../Dataset/dataset_74_wu'

In [4]:
OPTIONS = json.loads(open('../../Task/info.json', 'r').read())
OPTIONS['dataset'] = BASE_PATH.split('/')[-1].strip()
SCALING = OPTIONS.get('scaling', Normalization.DEFAULT)
OPTIONS

{'network': 'resaceunet_zu',
 'dataset': 'dataset_74_wu',
 'img_size': None,
 'scaling': 'normalize',
 'lr': 0.001,
 'loss': 'dice_focal',
 'batch_size': 2,
 'scheduler': 'plateau',
 'dropout': 0.1,
 'num_filters': 32,
 'ema': False,
 'epochs': 100,
 'n_trials': 1,
 'trial': 0}

### FONTES

- O `dataset_74_wu` não tem `images/` próprios: junta os volumes do `DATASET01` e do `DATASET02` como os `Format` deles gravaram, os `n_images` primeiros de cada um (`None` pega todos).
- A ordem importa: o split do `1 - Model` sorteia pela posição da linha. `DATASET01` = 110 do `dataset_74` e depois `DATASET02` = os 220 do `dataset_wu` reproduz byte a byte o `DataBase.csv` dos modelos salvos; com o wu na frente as contagens batem, mas os 15 volumes de teste caem todos no treino do `model_5`.
- A fonte cujo `DataBase.csv` não está no `scaling` da rodada tem o `Format` dela rodado aqui por papermill, como o `Task/index.py` faz, com o log em `Task/logs/Format_<fonte>_out.ipynb`.
- O `info.json` só é regravado depois, porque o `Format` de cada fonte o reescreve com o nome dela.
- No `'percentile'` cada fonte fica com o p01/p99 dela: as duas saem quase na mesma escala (±2,4 no `dataset_74`, ±2,7 no `dataset_wu`), e o p01/p99 da união mudaria o desvio em [0, 1] só de 0,20 para 0,19.

In [5]:
# RODA O Format DE UMA FONTE; O SystemExit É O FIM NORMAL DELE QUANDO A RODADA NÃO TEM TILES
def execute(path):
    output = os.path.abspath(f'../../Task/logs/Format_{Path(path).parent.name}_out.ipynb')

    try:
        pm.execute_notebook(path, output, kernel_name='python3', log_output=True, progress_bar=True, cwd=str(Path(path).parent))
    except pm.PapermillExecutionError as error:
        if error.ename != 'SystemExit':
            raise


for source in (DATASET01, DATASET02):
    database = f"{source['path']}/DataBase.csv"

    if not os.path.exists(database) or Normalization.read(database) != SCALING:
        execute(f"{source['path']}/Format.ipynb")

    print(f"{source['path']}: scaling={Normalization.read(database)!r}")

../dataset_74: scaling='normalize'
../dataset_wu: scaling='normalize'

In [6]:
with open('../../Task/info.json', 'w', encoding='utf-8') as file:
    json.dump(OPTIONS, file, ensure_ascii=False, indent=4)

In [7]:
d1_images = getFiles(f"{DATASET01['path']}/images", limit=DATASET01['n_images'])
d1_masks  = getFiles(f"{DATASET01['path']}/masks", limit=DATASET01['n_images'])

print(len(d1_images))
d1_images[:5]

110

['/home/grva-mint/Projects/Falhas/Dataset/dataset_74/images/img_0000.npy',
 '/home/grva-mint/Projects/Falhas/Dataset/dataset_74/images/img_0001.npy',
 '/home/grva-mint/Projects/Falhas/Dataset/dataset_74/images/img_0002.npy',
 '/home/grva-mint/Projects/Falhas/Dataset/dataset_74/images/img_0003.npy',
 '/home/grva-mint/Projects/Falhas/Dataset/dataset_74/images/img_0004.npy']

In [8]:
d2_images = getFiles(f"{DATASET02['path']}/images", limit=DATASET02['n_images'])
d2_masks  = getFiles(f"{DATASET02['path']}/masks", limit=DATASET02['n_images'])
print(len(d2_images))
d2_images[:5]

220

['/home/grva-mint/Projects/Falhas/Dataset/dataset_wu/images/0.npy',
 '/home/grva-mint/Projects/Falhas/Dataset/dataset_wu/images/1.npy',
 '/home/grva-mint/Projects/Falhas/Dataset/dataset_wu/images/10.npy',
 '/home/grva-mint/Projects/Falhas/Dataset/dataset_wu/images/100.npy',
 '/home/grva-mint/Projects/Falhas/Dataset/dataset_wu/images/101.npy']

In [9]:
df = pd.DataFrame()
df['img_path']  = d1_images + d2_images
df['mask_path'] = d1_masks  + d2_masks
df

,img_path,mask_path
0,/home/grva-mint/Projects/Falhas/Dataset/datase...,/home/grva-mint/Projects/Falhas/Dataset/datase...
1,/home/grva-mint/Projects/Falhas/Dataset/datase...,/home/grva-mint/Projects/Falhas/Dataset/datase...
2,/home/grva-mint/Projects/Falhas/Dataset/datase...,/home/grva-mint/Projects/Falhas/Dataset/datase...
3,/home/grva-mint/Projects/Falhas/Dataset/datase...,/home/grva-mint/Projects/Falhas/Dataset/datase...
4,/home/grva-mint/Projects/Falhas/Dataset/datase...,/home/grva-mint/Projects/Falhas/Dataset/datase...
...,...,...
325,/home/grva-mint/Projects/Falhas/Dataset/datase...,/home/grva-mint/Projects/Falhas/Dataset/datase...
326,/home/grva-mint/Projects/Falhas/Dataset/datase...,/home/grva-mint/Projects/Falhas/Dataset/datase...
327,/home/grva-mint/Projects/Falhas/Dataset/datase...,/home/grva-mint/Projects/Falhas/Dataset/datase...
328,/home/grva-mint/Projects/Falhas/Dataset/datase...,/home/grva-mint/Projects/Falhas/Dataset/datase...
329,/home/grva-mint/Projects/Falhas/Dataset/datase...,/home/grva-mint/Projects/Falhas/Dataset/datase...

In [10]:
info = []

for img_path, mask_path in tqdm(zip(df.img_path, df.mask_path)):
    img  = np.load(img_path)
    mask = np.load(mask_path)
    data = dict()

    data['id'] = Path(img_path).name
    data['img_min']  = np.min(img)
    data['img_max']  = np.max(img)
    data['img_mean'] = np.mean(img)
    data['img_std']  = np.std(img)

    data['msk_min'] = np.min(mask)
    data['msk_max'] = np.max(mask)
    data['shape']   = img.shape
    data['img_path']  = img_path
    data['mask_path'] = mask_path
    data['scaling'] = SCALING
    info.append(data)


df = pd.DataFrame(info)
print(df.img_path.iloc[2])
df

0it [00:00, ?it/s]

21it [00:00, 208.84it/s]

43it [00:00, 212.69it/s]

65it [00:00, 209.44it/s]

87it [00:00, 210.78it/s]

109it [00:00, 213.16it/s]

131it [00:00, 186.74it/s]

151it [00:00, 176.40it/s]

170it [00:00, 168.91it/s]

188it [00:01, 165.58it/s]

205it [00:01, 159.29it/s]

222it [00:01, 155.42it/s]

238it [00:01, 154.19it/s]

254it [00:01, 152.89it/s]

270it [00:01, 152.78it/s]

286it [00:01, 152.78it/s]

302it [00:01, 153.92it/s]

318it [00:01, 152.41it/s]

330it [00:01, 167.21it/s]

/home/grva-mint/Projects/Falhas/Dataset/dataset_74/images/img_0002.npy

,id,img_min,img_max,img_mean,img_std,msk_min,msk_max,shape,img_path,mask_path,scaling
0,img_0000.npy,0.0,1.0,0.529913,0.146943,0.0,1.0,"(128, 128, 128)",/home/grva-mint/Projects/Falhas/Dataset/datase...,/home/grva-mint/Projects/Falhas/Dataset/datase...,normalize
1,img_0001.npy,0.0,1.0,0.503019,0.121774,0.0,1.0,"(128, 128, 128)",/home/grva-mint/Projects/Falhas/Dataset/datase...,/home/grva-mint/Projects/Falhas/Dataset/datase...,normalize
2,img_0002.npy,0.0,1.0,0.469683,0.116922,0.0,1.0,"(128, 128, 128)",/home/grva-mint/Projects/Falhas/Dataset/datase...,/home/grva-mint/Projects/Falhas/Dataset/datase...,normalize
3,img_0003.npy,0.0,1.0,0.524412,0.117401,0.0,1.0,"(128, 128, 128)",/home/grva-mint/Projects/Falhas/Dataset/datase...,/home/grva-mint/Projects/Falhas/Dataset/datase...,normalize
4,img_0004.npy,0.0,1.0,0.524728,0.098068,0.0,1.0,"(128, 128, 128)",/home/grva-mint/Projects/Falhas/Dataset/datase...,/home/grva-mint/Projects/Falhas/Dataset/datase...,normalize
...,...,...,...,...,...,...,...,...,...,...,...
325,95.npy,0.0,1.0,0.491377,0.109896,0.0,1.0,"(128, 128, 128)",/home/grva-mint/Projects/Falhas/Dataset/datase...,/home/grva-mint/Projects/Falhas/Dataset/datase...,normalize
326,96.npy,0.0,1.0,0.474650,0.088855,0.0,1.0,"(128, 128, 128)",/home/grva-mint/Projects/Falhas/Dataset/datase...,/home/grva-mint/Projects/Falhas/Dataset/datase...,normalize
327,97.npy,0.0,1.0,0.454404,0.094104,0.0,1.0,"(128, 128, 128)",/home/grva-mint/Projects/Falhas/Dataset/datase...,/home/grva-mint/Projects/Falhas/Dataset/datase...,normalize
328,98.npy,0.0,1.0,0.474008,0.087315,0.0,1.0,"(128, 128, 128)",/home/grva-mint/Projects/Falhas/Dataset/datase...,/home/grva-mint/Projects/Falhas/Dataset/datase...,normalize
329,99.npy,0.0,1.0,0.461576,0.095507,0.0,1.0,"(128, 128, 128)",/home/grva-mint/Projects/Falhas/Dataset/datase...,/home/grva-mint/Projects/Falhas/Dataset/datase...,normalize

In [11]:
df.to_csv('DataBase.csv', index=None)
df

,id,img_min,img_max,img_mean,img_std,msk_min,msk_max,shape,img_path,mask_path,scaling
0,img_0000.npy,0.0,1.0,0.529913,0.146943,0.0,1.0,"(128, 128, 128)",/home/grva-mint/Projects/Falhas/Dataset/datase...,/home/grva-mint/Projects/Falhas/Dataset/datase...,normalize
1,img_0001.npy,0.0,1.0,0.503019,0.121774,0.0,1.0,"(128, 128, 128)",/home/grva-mint/Projects/Falhas/Dataset/datase...,/home/grva-mint/Projects/Falhas/Dataset/datase...,normalize
2,img_0002.npy,0.0,1.0,0.469683,0.116922,0.0,1.0,"(128, 128, 128)",/home/grva-mint/Projects/Falhas/Dataset/datase...,/home/grva-mint/Projects/Falhas/Dataset/datase...,normalize
3,img_0003.npy,0.0,1.0,0.524412,0.117401,0.0,1.0,"(128, 128, 128)",/home/grva-mint/Projects/Falhas/Dataset/datase...,/home/grva-mint/Projects/Falhas/Dataset/datase...,normalize
4,img_0004.npy,0.0,1.0,0.524728,0.098068,0.0,1.0,"(128, 128, 128)",/home/grva-mint/Projects/Falhas/Dataset/datase...,/home/grva-mint/Projects/Falhas/Dataset/datase...,normalize
...,...,...,...,...,...,...,...,...,...,...,...
325,95.npy,0.0,1.0,0.491377,0.109896,0.0,1.0,"(128, 128, 128)",/home/grva-mint/Projects/Falhas/Dataset/datase...,/home/grva-mint/Projects/Falhas/Dataset/datase...,normalize
326,96.npy,0.0,1.0,0.474650,0.088855,0.0,1.0,"(128, 128, 128)",/home/grva-mint/Projects/Falhas/Dataset/datase...,/home/grva-mint/Projects/Falhas/Dataset/datase...,normalize
327,97.npy,0.0,1.0,0.454404,0.094104,0.0,1.0,"(128, 128, 128)",/home/grva-mint/Projects/Falhas/Dataset/datase...,/home/grva-mint/Projects/Falhas/Dataset/datase...,normalize
328,98.npy,0.0,1.0,0.474008,0.087315,0.0,1.0,"(128, 128, 128)",/home/grva-mint/Projects/Falhas/Dataset/datase...,/home/grva-mint/Projects/Falhas/Dataset/datase...,normalize
329,99.npy,0.0,1.0,0.461576,0.095507,0.0,1.0,"(128, 128, 128)",/home/grva-mint/Projects/Falhas/Dataset/datase...,/home/grva-mint/Projects/Falhas/Dataset/datase...,normalize