In [1]:
import pandas as pd
import numpy as np
import glob, os, shutil, cv2, json, sys
from tqdm import tqdm

In [2]:
BASE_PATH = '../Dataset/dataset0'

In [3]:
def getFiles(path, limit=None, shuffle=False):
    target = sorted(glob.glob(os.path.join(path, '*')))
    if shuffle:
        np.random.shuffle(target) 
    return target[:limit]


OPTIONS = json.loads(open('../../Task/info.json', 'r').read())
OPTIONS

{'network': 'resaceunet2',
 'img_size': [16, 16, 16],
 'lr': 0.0005,
 'loss': 'dice_focal',
 'batch_size': 2,
 'scheduler': 'plateau',
 'dropout': 0.1,
 'num_filters': 16}

In [4]:
images = getFiles('images')
masks  = getFiles('masks')

print(images[0])
print(masks[0])

images/0.npy
masks/0.npy

In [5]:
df = pd.DataFrame()
df['img_path']  = [os.path.join(BASE_PATH, path) for path in images]
df['mask_path'] = [os.path.join(BASE_PATH, path) for path in masks]
df['shape']  = [np.load(path).shape for path in getFiles('images')]
df

,img_path,mask_path,shape
0,../Dataset/dataset0/images/0.npy,../Dataset/dataset0/masks/0.npy,"(128, 128, 128)"
1,../Dataset/dataset0/images/1.npy,../Dataset/dataset0/masks/1.npy,"(128, 128, 128)"
2,../Dataset/dataset0/images/10.npy,../Dataset/dataset0/masks/10.npy,"(128, 128, 128)"
3,../Dataset/dataset0/images/100.npy,../Dataset/dataset0/masks/100.npy,"(128, 128, 128)"
4,../Dataset/dataset0/images/101.npy,../Dataset/dataset0/masks/101.npy,"(128, 128, 128)"
...,...,...,...
215,../Dataset/dataset0/images/95.npy,../Dataset/dataset0/masks/95.npy,"(128, 128, 128)"
216,../Dataset/dataset0/images/96.npy,../Dataset/dataset0/masks/96.npy,"(128, 128, 128)"
217,../Dataset/dataset0/images/97.npy,../Dataset/dataset0/masks/97.npy,"(128, 128, 128)"
218,../Dataset/dataset0/images/98.npy,../Dataset/dataset0/masks/98.npy,"(128, 128, 128)"
219,../Dataset/dataset0/images/99.npy,../Dataset/dataset0/masks/99.npy,"(128, 128, 128)"

In [6]:
if OPTIONS.get('img_size') is None:
    df.to_csv('../DataBase.csv', index=None)
    display(df)
    sys.exit("Finalizando o programa: sem tiles nessa rodada")

# TILES

In [7]:
IMG_SIZE = tuple(OPTIONS['img_size'])
IMG_SIZE

(16, 16, 16)

In [8]:
class TilesBuilder:
    def __init__(self, target_size=(8, 64, 128), main_dir='tiles'):
        self.target_size = target_size
        self.main_dir    = main_dir

        if os.path.exists(main_dir):
            shutil.rmtree(main_dir)
        os.makedirs(main_dir)

    def update(self, file_path, target_dir, is_mask=False):
        folder = os.path.join(self.main_dir, target_dir)
        os.makedirs(folder, exist_ok=True)

        data = np.load(file_path)
        
        # ---------------------------------------------------------
        # CORREÇÃO DE ROTAÇÃO AQUI
        # Se o dado vem como (64, 128, 4) e precisa virar (4, 64, 128)
        # O eixo que está no índice 2 (tamanho 4) vai para o índice 0.
        # Os outros "escorregam" para a direita.
        # ---------------------------------------------------------
        data = np.transpose(data, (2, 0, 1)) 
        
        # Caso precise inverter também o X e o Y (ex: virar 4, 128, 64), 
        # a ordem do transpose seria (2, 1, 0).
        
        base_name     = os.path.splitext(os.path.basename(file_path))[0]
        z_t, y_t, x_t = self.target_size
        
        z_pad = (z_t - data.shape[0] % z_t) % z_t
        y_pad = (y_t - data.shape[1] % y_t) % y_t
        x_pad = (x_t - data.shape[2] % x_t) % x_t

        pad_mode    = 'constant' if is_mask else 'reflect'
        data_padded = np.pad(data, ((0, z_pad), (0, y_pad), (0, x_pad)), mode=pad_mode) if z_pad > 0 or y_pad > 0 or x_pad > 0 else data
            
        index = 0
        for z in range(0, data_padded.shape[0], z_t):
            for y in range(0, data_padded.shape[1], y_t):
                for x in range(0, data_padded.shape[2], x_t):
                    tile = data_padded[z:z+z_t, y:y+y_t, x:x+x_t]
                    save_path = os.path.join(folder, f'{base_name}_tile_{index}.npy')
                    
                    np.save(save_path, tile)
                    index = (index + 1)


tiles = TilesBuilder(target_size=IMG_SIZE, main_dir='tiles')
for img_path, mask_path in tqdm(zip(images, masks), total=len(df)):
    tiles.update(img_path,  'images/', is_mask=False)
    tiles.update(mask_path, 'masks/',  is_mask=True)

  0%|                                                                                                                                                                    | 0/220 [00:00<?, ?it/s]

  1%|█▍                                                                                                                                                          | 2/220 [00:00<00:17, 12.31it/s]

  2%|██▊                                                                                                                                                         | 4/220 [00:00<00:17, 12.44it/s]

  3%|████▎                                                                                                                                                       | 6/220 [00:00<00:17, 11.92it/s]

  4%|█████▋                                                                                                                                                      | 8/220 [00:00<00:17, 12.15it/s]

  5%|███████                                                                                                                                                    | 10/220 [00:00<00:17, 12.28it/s]

  5%|████████▍                                                                                                                                                  | 12/220 [00:00<00:16, 12.36it/s]

  6%|█████████▊                                                                                                                                                 | 14/220 [00:01<00:16, 12.36it/s]

  7%|███████████▎                                                                                                                                               | 16/220 [00:01<00:16, 12.31it/s]

  8%|████████████▋                                                                                                                                              | 18/220 [00:01<00:16, 12.23it/s]

  9%|██████████████                                                                                                                                             | 20/220 [00:01<00:16, 12.26it/s]

 10%|███████████████▌                                                                                                                                           | 22/220 [00:01<00:16, 12.29it/s]

 11%|████████████████▉                                                                                                                                          | 24/220 [00:01<00:15, 12.31it/s]

 12%|██████████████████▎                                                                                                                                        | 26/220 [00:02<00:15, 12.33it/s]

 13%|███████████████████▋                                                                                                                                       | 28/220 [00:02<00:15, 12.36it/s]

 14%|█████████████████████▏                                                                                                                                     | 30/220 [00:02<00:15, 12.35it/s]

 15%|██████████████████████▌                                                                                                                                    | 32/220 [00:02<00:15, 12.25it/s]

 15%|███████████████████████▉                                                                                                                                   | 34/220 [00:02<00:15, 12.19it/s]

 16%|█████████████████████████▎                                                                                                                                 | 36/220 [00:02<00:15, 12.21it/s]

 17%|██████████████████████████▊                                                                                                                                | 38/220 [00:03<00:14, 12.23it/s]

 18%|████████████████████████████▏                                                                                                                              | 40/220 [00:03<00:14, 12.21it/s]

 19%|█████████████████████████████▌                                                                                                                             | 42/220 [00:03<00:14, 12.19it/s]

 20%|███████████████████████████████                                                                                                                            | 44/220 [00:03<00:14, 12.20it/s]

 21%|████████████████████████████████▍                                                                                                                          | 46/220 [00:03<00:14, 12.23it/s]

 22%|█████████████████████████████████▊                                                                                                                         | 48/220 [00:03<00:14, 12.28it/s]

 23%|███████████████████████████████████▏                                                                                                                       | 50/220 [00:04<00:13, 12.30it/s]

 24%|████████████████████████████████████▋                                                                                                                      | 52/220 [00:04<00:13, 12.31it/s]

 25%|██████████████████████████████████████                                                                                                                     | 54/220 [00:04<00:13, 12.32it/s]

 25%|███████████████████████████████████████▍                                                                                                                   | 56/220 [00:04<00:13, 12.21it/s]

 26%|████████████████████████████████████████▊                                                                                                                  | 58/220 [00:04<00:13, 12.25it/s]

 27%|██████████████████████████████████████████▎                                                                                                                | 60/220 [00:04<00:13, 12.28it/s]

 28%|███████████████████████████████████████████▋                                                                                                               | 62/220 [00:05<00:12, 12.30it/s]

 29%|█████████████████████████████████████████████                                                                                                              | 64/220 [00:05<00:12, 12.33it/s]

 30%|██████████████████████████████████████████████▌                                                                                                            | 66/220 [00:05<00:15,  9.90it/s]

 31%|███████████████████████████████████████████████▉                                                                                                           | 68/220 [00:05<00:14, 10.54it/s]

 32%|█████████████████████████████████████████████████▎                                                                                                         | 70/220 [00:05<00:13, 11.03it/s]

 33%|██████████████████████████████████████████████████▋                                                                                                        | 72/220 [00:05<00:12, 11.39it/s]

 34%|████████████████████████████████████████████████████▏                                                                                                      | 74/220 [00:06<00:12, 11.66it/s]

 35%|█████████████████████████████████████████████████████▌                                                                                                     | 76/220 [00:06<00:12, 11.86it/s]

 35%|██████████████████████████████████████████████████████▉                                                                                                    | 78/220 [00:06<00:11, 12.01it/s]

 36%|████████████████████████████████████████████████████████▎                                                                                                  | 80/220 [00:06<00:11, 12.10it/s]

 37%|█████████████████████████████████████████████████████████▊                                                                                                 | 82/220 [00:06<00:11, 12.16it/s]

 38%|███████████████████████████████████████████████████████████▏                                                                                               | 84/220 [00:06<00:11, 12.11it/s]

 39%|████████████████████████████████████████████████████████████▌                                                                                              | 86/220 [00:07<00:11, 12.16it/s]

 40%|██████████████████████████████████████████████████████████████                                                                                             | 88/220 [00:07<00:10, 12.21it/s]

 41%|███████████████████████████████████████████████████████████████▍                                                                                           | 90/220 [00:07<00:10, 12.23it/s]

 42%|████████████████████████████████████████████████████████████████▊                                                                                          | 92/220 [00:07<00:10, 12.27it/s]

 43%|██████████████████████████████████████████████████████████████████▏                                                                                        | 94/220 [00:07<00:10, 12.27it/s]

 44%|███████████████████████████████████████████████████████████████████▋                                                                                       | 96/220 [00:07<00:10, 12.31it/s]

 45%|█████████████████████████████████████████████████████████████████████                                                                                      | 98/220 [00:08<00:09, 12.32it/s]

 45%|██████████████████████████████████████████████████████████████████████                                                                                    | 100/220 [00:08<00:09, 12.32it/s]

 46%|███████████████████████████████████████████████████████████████████████▍                                                                                  | 102/220 [00:08<00:09, 12.22it/s]

 47%|████████████████████████████████████████████████████████████████████████▊                                                                                 | 104/220 [00:08<00:09, 12.24it/s]

 48%|██████████████████████████████████████████████████████████████████████████▏                                                                               | 106/220 [00:08<00:09, 12.28it/s]

 49%|███████████████████████████████████████████████████████████████████████████▌                                                                              | 108/220 [00:08<00:09, 12.30it/s]

 50%|█████████████████████████████████████████████████████████████████████████████                                                                             | 110/220 [00:09<00:08, 12.32it/s]

 51%|██████████████████████████████████████████████████████████████████████████████▍                                                                           | 112/220 [00:09<00:08, 12.23it/s]

 52%|███████████████████████████████████████████████████████████████████████████████▊                                                                          | 114/220 [00:09<00:08, 12.30it/s]

 53%|█████████████████████████████████████████████████████████████████████████████████▏                                                                        | 116/220 [00:09<00:08, 12.29it/s]

 54%|██████████████████████████████████████████████████████████████████████████████████▌                                                                       | 118/220 [00:09<00:08, 12.31it/s]

 55%|████████████████████████████████████████████████████████████████████████████████████                                                                      | 120/220 [00:09<00:08, 12.19it/s]

 55%|█████████████████████████████████████████████████████████████████████████████████████▍                                                                    | 122/220 [00:10<00:08, 11.99it/s]

 56%|██████████████████████████████████████████████████████████████████████████████████████▊                                                                   | 124/220 [00:10<00:07, 12.06it/s]

 57%|████████████████████████████████████████████████████████████████████████████████████████▏                                                                 | 126/220 [00:10<00:10,  9.29it/s]

 58%|█████████████████████████████████████████████████████████████████████████████████████████▌                                                                | 128/220 [00:10<00:09,  9.60it/s]

 59%|███████████████████████████████████████████████████████████████████████████████████████████                                                               | 130/220 [00:10<00:08, 10.28it/s]

 60%|████████████████████████████████████████████████████████████████████████████████████████████▍                                                             | 132/220 [00:11<00:08, 10.81it/s]

 61%|█████████████████████████████████████████████████████████████████████████████████████████████▊                                                            | 134/220 [00:11<00:07, 11.20it/s]

 62%|███████████████████████████████████████████████████████████████████████████████████████████████▏                                                          | 136/220 [00:11<00:07, 11.51it/s]

 63%|████████████████████████████████████████████████████████████████████████████████████████████████▌                                                         | 138/220 [00:11<00:06, 11.76it/s]

 64%|██████████████████████████████████████████████████████████████████████████████████████████████████                                                        | 140/220 [00:11<00:06, 11.94it/s]

 65%|███████████████████████████████████████████████████████████████████████████████████████████████████▍                                                      | 142/220 [00:11<00:06, 12.02it/s]

 65%|████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                     | 144/220 [00:12<00:06, 12.11it/s]

 66%|██████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                   | 146/220 [00:12<00:06, 12.17it/s]

 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                  | 148/220 [00:12<00:06, 11.24it/s]

 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                 | 150/220 [00:12<00:06, 11.55it/s]

 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                               | 152/220 [00:12<00:05, 11.77it/s]

 70%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                              | 154/220 [00:12<00:05, 11.93it/s]

 71%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                            | 156/220 [00:13<00:05, 12.04it/s]

 72%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                           | 158/220 [00:13<00:05, 12.11it/s]

 73%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                          | 160/220 [00:13<00:04, 12.07it/s]

 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                        | 162/220 [00:13<00:04, 12.14it/s]

 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                       | 164/220 [00:13<00:04, 12.15it/s]

 75%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                     | 166/220 [00:13<00:04, 12.17it/s]

 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                    | 168/220 [00:14<00:04, 12.19it/s]

 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                   | 170/220 [00:14<00:04, 12.21it/s]

 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                 | 172/220 [00:14<00:03, 12.24it/s]

 79%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                | 174/220 [00:14<00:03, 12.24it/s]

 80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                              | 176/220 [00:14<00:03, 12.24it/s]

 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                             | 178/220 [00:14<00:03, 12.26it/s]

 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                            | 180/220 [00:15<00:03, 12.26it/s]

 83%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                          | 182/220 [00:15<00:03, 12.27it/s]

 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                         | 184/220 [00:15<00:05,  7.14it/s]

 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                       | 186/220 [00:15<00:04,  8.16it/s]

 85%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                      | 188/220 [00:16<00:03,  9.09it/s]

 86%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                     | 190/220 [00:16<00:03,  9.87it/s]

 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                   | 192/220 [00:16<00:02, 10.50it/s]

 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                  | 194/220 [00:16<00:02, 10.65it/s]

 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                | 196/220 [00:16<00:02, 11.11it/s]

 90%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌               | 198/220 [00:16<00:01, 11.39it/s]

 91%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████              | 200/220 [00:17<00:01, 11.50it/s]

 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 202/220 [00:17<00:01, 10.85it/s]

 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊           | 204/220 [00:17<00:01, 11.26it/s]

 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏         | 206/220 [00:17<00:01, 11.56it/s]

 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌        | 208/220 [00:17<00:01, 11.77it/s]

 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████       | 210/220 [00:17<00:00, 11.64it/s]

 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍     | 212/220 [00:18<00:00, 10.84it/s]

 97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊    | 214/220 [00:18<00:00, 11.05it/s]

 98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  | 216/220 [00:18<00:00, 11.40it/s]

 99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌ | 218/220 [00:18<00:00, 11.62it/s]

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 220/220 [00:18<00:00, 11.78it/s]

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 220/220 [00:18<00:00, 11.68it/s]

In [9]:
print(len(getFiles('tiles/images')), 'imagens geradas')

112640 imagens geradas

In [10]:
df = pd.DataFrame()
df['img_path']  = [os.path.join(BASE_PATH, path) for path in getFiles('tiles/images')]
df['mask_path'] = [os.path.join(BASE_PATH, path) for path in getFiles('tiles/masks')]
df['shape'] = [tiles.target_size for _ in range(len(df))]

df.to_csv('../DataBase.csv', index=None)
df

,img_path,mask_path,shape
0,../Dataset/dataset0/tiles/images/0_tile_0.npy,../Dataset/dataset0/tiles/masks/0_tile_0.npy,"(16, 16, 16)"
1,../Dataset/dataset0/tiles/images/0_tile_1.npy,../Dataset/dataset0/tiles/masks/0_tile_1.npy,"(16, 16, 16)"
2,../Dataset/dataset0/tiles/images/0_tile_10.npy,../Dataset/dataset0/tiles/masks/0_tile_10.npy,"(16, 16, 16)"
3,../Dataset/dataset0/tiles/images/0_tile_100.npy,../Dataset/dataset0/tiles/masks/0_tile_100.npy,"(16, 16, 16)"
4,../Dataset/dataset0/tiles/images/0_tile_101.npy,../Dataset/dataset0/tiles/masks/0_tile_101.npy,"(16, 16, 16)"
...,...,...,...
112635,../Dataset/dataset0/tiles/images/9_tile_95.npy,../Dataset/dataset0/tiles/masks/9_tile_95.npy,"(16, 16, 16)"
112636,../Dataset/dataset0/tiles/images/9_tile_96.npy,../Dataset/dataset0/tiles/masks/9_tile_96.npy,"(16, 16, 16)"
112637,../Dataset/dataset0/tiles/images/9_tile_97.npy,../Dataset/dataset0/tiles/masks/9_tile_97.npy,"(16, 16, 16)"
112638,../Dataset/dataset0/tiles/images/9_tile_98.npy,../Dataset/dataset0/tiles/masks/9_tile_98.npy,"(16, 16, 16)"
112639,../Dataset/dataset0/tiles/images/9_tile_99.npy,../Dataset/dataset0/tiles/masks/9_tile_99.npy,"(16, 16, 16)"